create_clock -period 10.00 -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports {user_start}]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {user_start}]

set_property PACKAGE_PIN V17 [get_ports user_choice[0]]
set_property PACKAGE_PIN V16 [get_ports user_choice[1]]
set_property PACKAGE_PIN W16 [get_ports user_choice[2]]
set_property IOSTANDARD LVCMOS18 [get_ports user_choice[0]]
set_property IOSTANDARD LVCMOS18 [get_ports user_choice[1]]
set_property IOSTANDARD LVCMOS18 [get_ports user_choice[2]]

set_property PACKAGE_PIN W17 [get_ports range_or_freq_divider_or_period[0]]
set_property PACKAGE_PIN W15 [get_ports range_or_freq_divider_or_period[1]]
set_property PACKAGE_PIN V15 [get_ports range_or_freq_divider_or_period[2]]
set_property PACKAGE_PIN W14 [get_ports range_or_freq_divider_or_period[3]]
set_property PACKAGE_PIN W13 [get_ports range_or_freq_divider_or_period[4]]
set_property IOSTANDARD LVCMOS18 [get_ports range_or_freq_divider_or_period[0]]
set_property IOSTANDARD LVCMOS18 [get_ports range_or_freq_divider_or_period[1]]
set_property IOSTANDARD LVCMOS18 [get_ports range_or_freq_divider_or_period[2]]
set_property IOSTANDARD LVCMOS18 [get_ports range_or_freq_divider_or_period[3]]
set_property IOSTANDARD LVCMOS18 [get_ports range_or_freq_divider_or_period[4]]

set_property PACKAGE_PIN V2 [get_ports max_value[0]]
set_property PACKAGE_PIN T3 [get_ports max_value[1]]
set_property PACKAGE_PIN T2 [get_ports max_value[2]]
set_property PACKAGE_PIN R3 [get_ports max_value[3]]
set_property PACKAGE_PIN W2 [get_ports max_value[4]]
set_property PACKAGE_PIN U1 [get_ports max_value[5]]
set_property PACKAGE_PIN T1 [get_ports max_value[6]]
set_property PACKAGE_PIN R2 [get_ports max_value[7]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[0]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[1]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[2]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[3]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[4]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[5]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[6]]
set_property IOSTANDARD LVCMOS18 [get_ports max_value[7]]

set_property PACKAGE_PIN A14 [get_ports output_wave[0]]
set_property PACKAGE_PIN A16 [get_ports output_wave[1]]
set_property PACKAGE_PIN B15 [get_ports output_wave[2]]
set_property PACKAGE_PIN B16 [get_ports output_wave[3]]
set_property PACKAGE_PIN A15 [get_ports output_wave[4]]
set_property PACKAGE_PIN A17 [get_ports output_wave[5]]
set_property PACKAGE_PIN C15 [get_ports output_wave[6]]
set_property PACKAGE_PIN C16 [get_ports output_wave[7]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[0]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[1]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[2]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[3]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[4]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[5]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[6]]
set_property IOSTANDARD LVCMOS18 [get_ports output_wave[7]]

set_property PACKAGE_PIN U16 [get_ports running_function[0]]
set_property PACKAGE_PIN E19 [get_ports running_function[1]]
set_property PACKAGE_PIN U19 [get_ports running_function[2]]
set_property PACKAGE_PIN V19 [get_ports running_function[3]]
set_property PACKAGE_PIN W18 [get_ports running_function[4]]
set_property PACKAGE_PIN U15 [get_ports running_function[5]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[0]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[1]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[2]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[3]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[4]]
set_property IOSTANDARD LVCMOS18 [get_ports running_function[5]]